# Generated by Django 3.2.6 on 2021-09-22 08:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FestAccomodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day1', models.BooleanField()),
                ('day2', models.BooleanField()),
                ('day3', models.BooleanField()),
                ('day4', models.BooleanField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Festevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(default=None, max_length=255)),
                ('image', models.ImageField(blank=True, default=None, upload_to='uploads/events/event_logo')),
                ('eventprice', models.CharField(default=None, max_length=4)),
                ('eventdescription', models.TextField(blank=True, default=None, max_length=1000, null=True)),
                ('event_type', models.CharField(blank=True, choices=[('technical', 'Technical'), ('non-technical', 'Non-Technical'), ('Cultural', 'Cultural'), ('Management', 'Management')], max_length=50, null=True)),
                ('venue', models.CharField(choices=[('0', 'Patkar College'), ('1', "Bhavan's College"), ('2', 'Virtual')], default='2', max_length=30, null=True)),
                ('participation_type', models.CharField(blank=True, choices=[('individual', 'Individual'), ('team', 'Team')], max_length=50, null=True)),
                ('min_participants', models.IntegerField(default=1, null=True)),
                ('max_participants', models.IntegerField(default=4, null=True)),
                ('prize', models.IntegerField(blank=True, default=None, null=True)),
                ('time', models.TimeField(default='12:00:00')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('coordinators', models.CharField(blank=True, choices=[('amir', 'Amir'), ('roshith', 'Roshith')], default=None, max_length=50, null=True)),
                ('contact_name1', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('contact_phone1', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('contact_email1', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_image1', models.ImageField(blank=True, default=None, null=True, upload_to='uploads/events/event_contact/')),
                ('contact_name2', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('contact_phone2', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('contact_email2', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('contact_image2', models.ImageField(blank=True, default=None, null=True, upload_to='uploads/events/event_contact/')),
                ('sponsor1', models.ImageField(blank=True, upload_to='uploads/events/events_sponsors/')),
                ('sponsor2', models.ImageField(blank=True, upload_to='uploads/events/events_sponsors/')),
                ('sponsor3', models.ImageField(blank=True, upload_to='uploads/events/events_sponsors/')),
                ('sponsor4', models.ImageField(blank=True, upload_to='uploads/events/events_sponsors/')),
                ('sponsor5', models.ImageField(blank=True, upload_to='uploads/events/events_sponsors/')),
                ('one_liner', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignInUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=250)),
                ('last_name', models.CharField(default=None, max_length=250)),
                ('gender', models.CharField(blank=True, choices=[('0', 'Female'), ('1', 'Male'), ('2', 'Other')], default=None, max_length=10, null=True)),
                ('phone', models.CharField(default=None, max_length=11)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('password', models.CharField(default=None, max_length=254)),
                ('Terms_and_Conditions', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=250)),
                ('last_name', models.CharField(default=None, max_length=250)),
                ('phone', models.CharField(default=None, max_length=11)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('password', models.CharField(default=None, max_length=254)),
                ('participation_code', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=4, lowercase=True, unique=True)),
                ('universitiy', models.CharField(blank=True, choices=[('mu', 'Mumbai University'), ('gtu', 'Gujarat Technological University'), ('marwadi', 'Marwadi University'), ('atmiya', 'Atmiya University'), ('rk', 'RK University'), ('others', 'Others')], max_length=50, null=True)),
                ('enrolment_number', models.CharField(blank=True, max_length=50, null=True)),
                ('college', models.CharField(blank=True, max_length=10, null=True)),
                ('participated', models.BooleanField(null=True)),
                ('winner', models.BooleanField(null=True)),
                ('place_secured', models.IntegerField(blank=True, null=True)),
                ('event_name', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='management.festevent')),
            ],
        ),
        migrations.CreateModel(
            name='Parti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_participated', models.ManyToManyField(to='management.Festevent')),
                ('participated_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.signinuser')),
            ],
        ),
    ]
