# Generated by Django 3.2.6 on 2021-10-02 07:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], default=None, max_length=10, null=True)),
                ('mobile', models.CharField(default=None, max_length=11)),
                ('universitiy', models.CharField(blank=True, choices=[('mu', 'Mumbai University'), ('gtu', 'Gujarat Technological University'), ('marwadi', 'Marwadi University'), ('atmiya', 'Atmiya University'), ('rk', 'RK University'), ('others', 'Others')], max_length=50, null=True)),
                ('college', models.CharField(blank=True, max_length=10, null=True)),
                ('profile_image', models.ImageField(blank=True, default='uploads/events/profile_images/dummy_boy2.png', null=True, upload_to='uploads/events/profile_images/')),
                ('Terms_and_Conditions', models.BooleanField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FestAccomodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day1', models.BooleanField()),
                ('day2', models.BooleanField()),
                ('day3', models.BooleanField()),
                ('day4', models.BooleanField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Festevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(default=None, max_length=255)),
                ('image', models.ImageField(blank=True, default=None, upload_to='uploads/events/event_logo')),
                ('fees', models.CharField(default=None, max_length=4)),
                ('eventdescription', models.TextField(blank=True, default=None, max_length=1000, null=True)),
                ('event_type', models.CharField(blank=True, choices=[('Technical', 'Technical'), ('Non-technical', 'Non-Technical'), ('Cultural', 'Cultural'), ('Management', 'Management')], max_length=50, null=True)),
                ('venue', models.CharField(choices=[('Patkar College 😒', 'Patkar College 😒'), ("Bhavan's College 😌", "Bhavan's College 😌"), ('Virtual', 'Virtual')], default='2', max_length=30, null=True)),
                ('participation_type', models.CharField(blank=True, choices=[('👱🏻Individual', ' 👱🏻 Individual'), ('👨\u200d👩\u200d👦Team', '👨\u200d👩\u200d👦Team ')], max_length=50, null=True)),
                ('min_participants', models.IntegerField(default=1, null=True)),
                ('max_participants', models.IntegerField(default=4, null=True)),
                ('prize', models.IntegerField(blank=True, default=None, null=True)),
                ('event_on_day', models.CharField(blank=True, choices=[('1', 'Day 1️⃣'), ('2', 'Day 2️⃣'), ('3', 'Day 3️⃣'), ('4', 'Day 4️⃣'), ('5', 'Day 5️⃣'), ('6', 'Day 6')], default='Choose Day', max_length=20)),
                ('time', models.TimeField(default='12:00:00')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('coordinators', models.CharField(blank=True, choices=[('Amir', 'Amir'), ('Roshith', 'Roshith')], default=None, max_length=50, null=True)),
                ('contact_name1', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('contact_phone1', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('contact_email1', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_image1', models.ImageField(blank=True, default=None, null=True, upload_to='uploads/events/event_contact/')),
                ('contact_name2', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('contact_phone2', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('contact_email2', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('contact_image2', models.ImageField(blank=True, default=None, null=True, upload_to='uploads/events/event_contact/')),
                ('sponsor1', models.ImageField(blank=True, upload_to='uploads/events/events_sponsors/')),
                ('sponsor2', models.ImageField(blank=True, upload_to='uploads/events/events_sponsors/')),
                ('sponsor3', models.ImageField(blank=True, upload_to='uploads/events/events_sponsors/')),
                ('sponsor4', models.ImageField(blank=True, upload_to='uploads/events/events_sponsors/')),
                ('sponsor5', models.ImageField(blank=True, upload_to='uploads/events/events_sponsors/')),
                ('one_liner', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignInUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=250)),
                ('last_name', models.CharField(default=None, max_length=250)),
                ('gender', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], default=None, max_length=10, null=True)),
                ('phone', models.CharField(default=None, max_length=11)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('universitiy', models.CharField(blank=True, choices=[('mu', 'Mumbai University'), ('gtu', 'Gujarat Technological University'), ('marwadi', 'Marwadi University'), ('atmiya', 'Atmiya University'), ('rk', 'RK University'), ('others', 'Others')], max_length=50, null=True)),
                ('college', models.CharField(blank=True, max_length=10, null=True)),
                ('password', models.CharField(default=None, max_length=254)),
                ('profile_image', models.ImageField(blank=True, default='uploads/events/profile_images/dummy_boy2.png', null=True, upload_to='uploads/events/profile_images/')),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2021, 10, 2, 13, 26, 55, 753030))),
                ('Terms_and_Conditions', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('1', 'Title Sponsor'), ('2', 'Online Media Sponsors'), ('3', 'Normal Sponsor'), ('4', 'Event Sponsor')], max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('name_shown', models.CharField(blank=True, default='', max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='uploads/events/sponsors/')),
                ('url', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Sponsors',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=250)),
                ('last_name', models.CharField(default=None, max_length=250)),
                ('phone', models.CharField(default=None, max_length=11)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('password', models.CharField(default=None, max_length=254)),
                ('participation_code', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=7, lowercase=True, unique=True)),
                ('universitiy', models.CharField(blank=True, choices=[('mu', 'Mumbai University'), ('gtu', 'Gujarat Technological University'), ('marwadi', 'Marwadi University'), ('atmiya', 'Atmiya University'), ('rk', 'RK University'), ('others', 'Others')], max_length=50, null=True)),
                ('enrolment_number', models.CharField(blank=True, max_length=50, null=True)),
                ('college', models.CharField(blank=True, max_length=10, null=True)),
                ('profile_image', models.ImageField(blank=True, default=None, null=True, upload_to='uploads/events/profile_images/')),
                ('participated', models.BooleanField(null=True)),
                ('winner', models.BooleanField(null=True)),
                ('place_secured', models.IntegerField(blank=True, null=True)),
                ('event_name', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='management.festevent')),
            ],
        ),
        migrations.CreateModel(
            name='Parti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_participated', models.ManyToManyField(to='management.Festevent')),
                ('participated_user', models.ManyToManyField(default=None, to='management.FestAccomodation')),
            ],
        ),
    ]
