# Generated by Django 3.2.6 on 2021-08-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='email',
            field=models.EmailField(default=False, max_length=254),
        ),
        migrations.AddField(
            model_name='participants',
            name='password',
            field=models.CharField(default=False, max_length=254),
        ),
        migrations.AddField(
            model_name='participants',
            name='phone',
            field=models.CharField(default=False, max_length=11),
        ),
    ]
