# Generated by Django 3.2.6 on 2021-10-08 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signinuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 8, 16, 35, 4, 215130)),
        ),
    ]
