# Generated by Django 3.2.6 on 2021-09-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_parti_participated_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parti',
            name='participated_user',
        ),
        migrations.AddField(
            model_name='parti',
            name='participated_user',
            field=models.ManyToManyField(default=None, null=True, to='management.FestAccomodation'),
        ),
    ]
