# Generated by Django 3.2.6 on 2021-10-08 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_signinuser_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='universitiy',
            new_name='university',
        ),
        migrations.AlterField(
            model_name='signinuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 8, 17, 1, 47, 403573)),
        ),
    ]
