# Generated by Django 3.2.6 on 2021-09-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20210922_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parti',
            name='participated_user',
            field=models.ManyToManyField(default=None, to='management.FestAccomodation'),
        ),
    ]
