# Generated by Django 3.2.6 on 2021-10-08 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20211008_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signinuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 8, 17, 10, 19, 867534)),
        ),
    ]
