# Generated by Django 3.2.6 on 2021-09-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_parti_participated_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='festevent',
            name='event_on_day',
            field=models.CharField(blank=True, choices=[('1', 'Day 1'), ('2', 'Day 2'), ('3', 'Day 3'), ('4', 'Day 4'), ('5', 'Day 5'), ('6', 'Day 6')], default='Choose Day', max_length=20),
        ),
    ]
