# Generated by Django 3.2.6 on 2021-09-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20210922_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='profile_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/events/profile_images/'),
        ),
    ]
