# Generated by Django 3.2.6 on 2021-09-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_participant_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=' ', max_length=255)),
                ('thumbnail', models.ImageField(blank=True, upload_to='uploads/events/choice_images/')),
            ],
        ),
    ]
