# Generated by Django 3.2.6 on 2021-09-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_countries'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Countries',
        ),
    ]
