# Generated by Django 3.2.6 on 2021-09-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_sponsors'),
    ]

    operations = [
        migrations.AddField(
            model_name='signinuser',
            name='college',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='signinuser',
            name='universitiy',
            field=models.CharField(blank=True, choices=[('mu', 'Mumbai University'), ('gtu', 'Gujarat Technological University'), ('marwadi', 'Marwadi University'), ('atmiya', 'Atmiya University'), ('rk', 'RK University'), ('others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='signinuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], default=None, max_length=10, null=True),
        ),
    ]
