# Generated by Django 3.2.6 on 2021-09-22 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20210922_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='signinuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 22, 22, 52, 49, 978881)),
        ),
    ]
